---
title: "Sales Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library("flexdashboard")
library("ggplot2")
library("tidyverse")
library("plotly")
library("ggmap")
library("knitr")
library("leaflet")
library("DT")
library(sp)
library(rnaturalearth)
library(highcharter)
library(shiny)

# import the data

df<-read_csv("Data/countries_geographic_coordinatesISO.csv")
country_coord<-read_csv("Data/data.csv")

#join the 2 tables to get the geographic coordinates of the countries

df<- inner_join(df,country_coord)
                
# amend the data types

df$InvoiceDate<- as.Date(df$InvoiceDate,format = "%m/%d/%Y")
df$CustomerID <- as.character(df$CustomerID)
df$UnitPrice<- round(df$UnitPrice)


# Map set up

map <- ne_countries()
names(map)[names(map) == "iso_a3"] <- "ISO3"
names(map)[names(map) == "name"] <- "NAME"



CountryData<- aggregate(UnitPrice ~ CountCode, df, sum)


map$Revenue <- CountryData$UnitPrice[match(map$ISO3, CountryData$CountCode)]

```


Dash {data-icon="fa-globe"} 
==========================================================

Row 
--------------------------------------

### Number of Transactions

```{r}

AnnualSales <- df %>% 
  distinct(InvoiceNo) %>% 
  nrow()
valueBox(value= AnnualSales,icon = "fa-usd", caption ="Number of Transactions",color = "Coral")

```

### Gross Annual Revenue

```{r}

AnnualRevenue <- scales::dollar(sum(df$UnitPrice)-sum((filter(df,df$Quantity < 0)$UnitPrice)))
valueBox(value = AnnualRevenue,icon = "fa-usd",caption = "Gross Annual Revenue", color = 'CornflowerBlue')
```

### Refunds

```{r}

refund <- round((sum((filter(df,df$Quantity < 0)$UnitPrice))/sum(df$UnitPrice))*100,1)
gauge(refund, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))

```

Column {.sidebar data-width=200}
-------------------------------------

```{r}
minvalue <- floor(min(map$Revenue, na.rm = TRUE))
maxvalue <- ceiling(max(map$Revenue, na.rm = TRUE))

sliderInput("rangevalues",
  label = "Revenue values:",
  min = minvalue, max = maxvalue,
  value = c(minvalue, maxvalue)
)
           
```


Column {data-width=500}
-------------------------------------
    
### Map
    
```{r}



pal <- colorBin(
  palette = "viridis", domain = map$Revenue ,
  #bins = seq(0, max(map$Revenue, na.rm = TRUE) + 10, by = 10)
)


map$labels <- paste0(
  "<strong> Country: </strong> ",
  map$NAME, "<br/> ",
  "<strong> Revenue: </strong> ",
  map$Revenue , "<br/> "
) %>%
  lapply(htmltools::HTML)


mapFiltered <- reactive({
  rowsinrangeslider <- which(map$Revenue >= input$rangevalues[1] &
    map$Revenue <= input$rangevalues[2])
  map[rowsinrangeslider, ]
})

renderLeaflet({
  if (nrow(mapFiltered()) == 0) {
    return(NULL)
  }

leaflet(mapFiltered()) %>%
  addTiles() %>%
  setView(lng = 0, lat = 30, zoom = 2) %>%
  addPolygons(
    fillColor = ~ pal(Revenue),
    color = "white",
    fillOpacity = 0.7,
    label = ~labels,
    highlight = highlightOptions(
      color = "black",
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~Revenue,
    opacity = 0.7, title = "Revenue"
  )
})
  
```   
 
### Table
    
```{r}

revenue<- aggregate(Quantity ~ StockCode, df, sum)%>%
  filter(Quantity>0)

renderDT({
DT::datatable(revenue,
  rownames = FALSE, options = list(pageLength = 10)
)
})
```

Column {data-width=600}
-------------------------------------

### Sales monthly performance

```{r}

time_revenue<-aggregate(UnitPrice ~ InvoiceDate, df, sum)
  
renderHighchart({
time_revenue%>% 
 
  hchart('line', hcaes(x = 'InvoiceDate', y = 'UnitPrice'))
  
})
```


### Analysis

#### This dashboard represents the sales performance of an online retailer. You can find the data set [here](https://www.kaggle.com/carrie1/ecommerce-data). The data set contains 541,909 capturing the period between 2010 – 2011.

